### ISSUE TITLE
Ask for code

### ISSUE THREAD

**Issue by mimiyuyu** [Franblueee/SmMIL#1]
Hi Francisco M. Castro-Macías,

I hope this message finds you well. I have thoroughly read your article and I must say, I'm quite inspired by the work you've done. Your insights have been incredibly valuable to my understanding of the topic.

I'm reaching out to express my interest in the code that was used in your study. I believe that making the code publicly available on GitHub would be a great asset to the community, as it would allow for more in-depth discussions and collaborative exploration of the concepts presented in your article.

Would it be possible for you to share when you might consider releasing the code? I'm genuinely excited about the prospect of diving into the code and contributing to the conversation around your research.

Thank you for your time and for considering my request. I look forward to any updates you can provide.

Best regards,

Jiayu

**Comment by Franblueee** [comment]
Hi!

I am glad that you find our work interesting!

Sorry for the delay, I have been very busy in the last month. The code will be up in the next few days (before NeurIPS24). 

Best, 

Fran

**Comment by Franblueee** [comment]
The code is up, closing this issue!
